-   id: emqx-check-year-updated
    name: check if year is updated in copyrights, license, etc.
    description: check if year is updated in copyrights, license, etc.
    entry: check-date
    language: python
    stages: [pre-commit, manual]